# Generated by Django 3.2 on 2021-04-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='name',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='price',
            field=models.FloatField(blank=True, help_text='in rupees', null=True),
        ),
    ]
