# Generated by Django 3.2.4 on 2021-07-13 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_model_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('com_id', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prd_com', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
