# Generated by Django 3.2.4 on 2021-07-13 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_comment_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment_model',
            new_name='product_comment',
        ),
    ]
