# Generated by Django 3.2.4 on 2021-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_model',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
