# Generated by Django 3.2.4 on 2021-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210713_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_list',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.order_model'),
        ),
    ]
