# Generated by Django 3.2.4 on 2023-10-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_sales_list_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_list',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Order Placed', 'Order Placed'), ('Dispatched', 'Dispatched')], default='Order Placed', max_length=50),
        ),
    ]
