# Generated by Django 3.2.4 on 2023-10-13 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_sales_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_list',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales_list',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='cancel_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('net_price', models.FloatField(blank=True, null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Order Placed', 'Order Placed'), ('Dispatched', 'Dispatched')], default='Order Placed', max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_order_costumer1', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='products.order_model')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_order_owner1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
