# Generated by Django 3.2.4 on 2023-10-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20231013_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_orders',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_list',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancel_orders',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Preparing your order', 'Preparing your order'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50),
        ),
        migrations.AlterField(
            model_name='sales_list',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Preparing your order', 'Preparing your order'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50),
        ),
    ]
