# Generated by Django 3.2.4 on 2023-10-13 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20231013_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_list',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
