# Generated by Django 3.2.4 on 2023-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_sales_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_list',
            name='adress',
            field=models.TextField(blank=True, default='sukhna', null=True),
        ),
        migrations.AlterField(
            model_name='sales_list',
            name='name',
            field=models.CharField(blank=True, default='pragya', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_list',
            name='number',
            field=models.IntegerField(blank=True, default='9437326713', null=True),
        ),
    ]
