# Generated by Django 3.2.4 on 2023-10-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_auto_20231014_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='status',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New', 'New')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_prd', to='products.product_model')),
            ],
        ),
    ]
