# Generated by Django 3.2.4 on 2023-10-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20231014_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='status',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New', 'New')], default='New', max_length=100, null=True),
        ),
    ]
