# Generated by Django 3.2.4 on 2023-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20231014_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
