# Generated by Django 3.2.4 on 2023-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='ratings',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
