# Generated by Django 3.2.4 on 2023-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_model_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='status',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New', 'New'), ('Out of Stock', 'Out of Stock')], default='New', max_length=100, null=True),
        ),
    ]
