# Generated by Django 3.2.4 on 2023-10-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_model_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='author',
        ),
    ]
