# Generated by Django 3.2.4 on 2023-10-15 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0027_alter_product_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
