# Generated by Django 3.2.4 on 2023-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_model_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='balck_finding',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='country',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='lustre',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='metal',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='occasion',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='rusting',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='stone',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='weight',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
