# Generated by Django 3.2.4 on 2023-10-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20231015_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_model',
            old_name='balck_finding',
            new_name='back_finding',
        ),
    ]
