# Generated by Django 3.2.4 on 2023-10-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_product_model_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='image4',
        ),
    ]
