# Generated by Django 3.2.4 on 2023-10-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_product_model_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
